### ISSUE TITLE
Implement main menu

### ISSUE THREAD

**Issue by NicolajRJensen** [SeaGruppen/SEA#1]
# TODO list
- [x] Create overall layout
  - [x] Button for super user menu
  - [x] Button for experimenter menu
  - [x] ?(Button for importing new survey)?
- [x] Implement the navigation
  - [x] Internally in login screen
  - [x] From login screen to Super user menu
  - [x] From login screen to experimenter menu
- [x] Implement login features 
  - [x] Super user password
  - [x] Experimenter pincode
  - [x] Only allow login press when there is actual required input
    - Experimenter login:
      - PIN code length is 6 chars
      - PIN code only consists of digits
    - Super user login:
      - Username is anything
      - Password is anything

# UI and Navigation
I've the following proposal for UI and navigation (this is unpolished :)):
![UI+navigation](https://github.com/SeaGruppen/SEA/assets/60060937/546bdcc4-ecb8-4487-a799-dcf47d6ed977)
